workflows:

  my-workflow:
    instance_type: windows_x2                # specify linux or linux_2 for Linux instances; mac_mini or mac_pro for macOS instances
    max_build_duration: 120
    scripts:
      - name: Install npm dependencies
        script: npm install

      - name: Tests                       # Insert before the build command
        script: npm test

      - name: Build ipa for distribution
        script: xcode-project build-ipa --workspace "$FCI_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme $XCODE_SCHEME

      - name: Build Android app
        script: cd android && ./gradlew assembleRelease
